{% load_yaml as lookup %}
FreeBSD:
    package: unbound
    service: unbound
    config_file: /usr/local/etc/unbound/unbound.conf
Debian:
    package: unbound
    service: unbound
    config_file: /etc/unbound/unbound.conf
Ubuntu:
    package: unbound
    service: unbound
    config_file: /etc/unbound/unbound.conf
{% endload %}

{% load_yaml as rawmap %}
server:
    interfaces:
        - 0.0.0.0
        - ::0
    acls:
        - 10.0.0.0/8 allow
        - 172.16.0.0/12 allow
        - 192.168.0.0/16 allow
{% endload %}
